---
- name: Install steamcmd and Arma
  hosts: arma
  become: yes
  become_user: "{{ user }}"
  
  vars:
    user: arma
    home: "/srv/{{ user }}"

  tasks:
  - name: Create user
    become: yes
    become_user: root
    ansible.builtin.user:
      name: "{{ user }}"
      system: yes
      home: "{{ home }}"
      shell: /bin/bash
  - name: Set PATH
    ansible.builtin.lineinfile:
      path: "{{ home }}/.bashrc"
      line: "PATH={{ repodir }}/bin:$PATH"
  - name: Clone server handling repo
    ansible.builtin.git:
      repo: https://github.com/zeusops/server-handling.git
      dest: "{{ home }}/server-handling"
  - name: Symlinks
    ansible.builtin.file:
      src: "{{ home }}/server-handling"
      dest: "{{ home }}/files"
      state: link
  - name: Install steamcmd
    become: yes
    become_user: root
    import_role:
      name: lutangar.steamcmd
    vars:
      # FIXME: this doesn't actually override the variable as expected, had to
      # truncate vars/Debian.yml in the role for this to apply
      steamcmd_packages:
      - lib32gcc-s1
      steamcmd_create_user: no
      steamcmd_user: "{{ user }}"
      steamcmd_user_home: "{{ home }}/"
      steamcmd_directory: "{{ home }}/steamcmd/"
      steamcmd_steam:
        username: zeusoperations
        password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          36383861316535363530346361643439373262343438643365323236656430633461616164353930
          3438373433636666356566343034613033393535383464330a333834353539646565383361383236
          65396537366465636232366563656166356132633838366465666132656338323834626162313436
          3365326635353837320a356261633236623732366632336232646135616265303364633730376130
          3066
