---
- name: Common setup
  hosts: all

  vars:
    ssh_users:
    - sami
    - root
    - arma
    git_config_users:
    - sami
    - root
    git_configs:
    - { config: user.name,  value: Sami Laine }
    - { config: user.email, value: sami.v.laine@gmail.com }

  tasks:
  - name: Add cockpit-navigator repo
    block:
      - name: Add 45drives key
        ansible.builtin.get_url:
          url: https://repo.45drives.com/key/gpg.asc
          dest: /etc/apt/trusted.gpg.d/45drives-archive-keyring.asc

      - name: Add 45drives repo
        ansible.builtin.apt_repository:
          repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/45drives-archive-keyring.asc] https://repo.45drives.com/debian focal main"
          state: present
  - name: Install packages
    ansible.builtin.apt:
      name:
        - zsh
        - git
        - tmux
        - byobu
        - ufw
        - fail2ban
        - etckeeper
        - ncdu
        - aptitude
        - apt-file
        - python3-venv
        - molly-guard
        - cockpit
        - cockpit-podman
        # store past metrics
        - cockpit-pcp
        - cockpit-machines
        - cockpit-navigator
        # certificate generator for cockpit
        - sscg
        - unzip
        # Includes the checkrestart command
        - debian-goodies
      update_cache: true
  - name: Set git default branch
    community.general.git_config:
      scope: system
      name: init.defaultBranch
      value: main
  - name: Create users
    ansible.builtin.user:
      name: sami
      shell: /usr/bin/zsh
  - name: Set git configs
    become: true
    become_user: "{{ item.0 }}"
    community.general.git_config:
      scope: global
      name: "{{ item.1.config }}"
      value: "{{ item.1.value }}"
    loop: "{{ git_config_users|product(git_configs)|list }}"
  - name: Add SSH keys
    ansible.posix.authorized_key:
      user: "{{ item }}"
      key: "{{ lookup('file', 'files/pubkeys/{{ item }}') }}"
      exclusive: True
    loop: "{{ ssh_users }}"
  - name: Set vim as editor
    community.general.alternatives:
      name: editor
      path: /usr/bin/vim.basic
  - name: Enable ufw
    community.general.ufw:
      state: enabled
      policy: reject
  - name: Allow SSH
    community.general.ufw:
      rule: allow
      name: OpenSSH
  - name: Start fail2ban
    ansible.builtin.systemd:
      state: started
      enabled: yes
      name: fail2ban
  - name: Mask fwupd service
    # A bug in systemd causes the service to always fail. A fix has been
    # created, expected to release any day now. See the following links for
    # further info:
    # https://github.com/fwupd/fwupd/issues/3037
    # https://github.com/fwupd/fwupd/commit/0c9ac226c976836b89e8a3736145f162f43f4691
    # https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1969976
    ansible.builtin.systemd:
      name: "{{ item }}"
      state: stopped
      masked: yes
    loop:
    - fwupd-refresh.service
    - fwupd-refresh.timer
