---
- name: Common setup
  hosts: all

  tasks:
  - name: Install zsh
    ansible.builtin.apt:
      name:
        - zsh
        - git
        - tmux
        - byobu
      update_cache: true
  - name: Set git default branch
    community.general.git_config:
      scope: system
      name: init.defaultBranch
      value: main
  - name: Create users
    ansible.builtin.user:
      name: sami
      shell: /usr/bin/zsh
  - name: Set git configs
    become: true
    become_user: "{{ item.0 }}"
    community.general.git_config:
      scope: global
      name: "{{ item.1.config }}"
      value: "{{ item.1.value }}"
    loop: "{{ git_config_users|product(git_configs)|list }}"
    vars:
      git_configs:
      - { config: user.name,  value: Sami Laine }
      - { config: user.email, value: sami.v.laine@gmail.com }
      git_config_users:
      - sami
      - root
  - name: Add SSH keys (root)
    ansible.posix.authorized_key:
      user: root
      key: "{{ lookup('file', 'files/pubkeys/root') }}"
      exclusive: True
  - name: Add SSH keys (sami)
    ansible.posix.authorized_key:
      user: sami
      key: "{{ lookup('file', 'files/pubkeys/sami') }}"
      exclusive: True
  - name: Set vim as editor
    community.general.alternatives:
      name: editor
      path: /usr/bin/vim.basic
