---
- name: Manage containers
  hosts: containerhost

  roles:
  - chasinglogic.podman

  vars:
    podman_services:
    - image_name: n1try/wakapi
      description: Wakapi server
      publish:
      - 127.0.0.1:3000:3000
      volumes:
      - /opt/wakapi/data:/data
      service_name: wakapi
      after:
      - network.target
      timeout_start_sec: 1m
    # Don't run `apt upgrade` every time something changes
    podman_upgrade_system: no
